export const GET_RANDOM_USER_STARTED = 'GET_RANDOM_USER_STARTED';
export const GET_RANDOM_USER_SUCCESS = 'GET_RANDOM_USER_SUCCESS';
export const SET_USER = 'SET_USER';
export const DELETE_USER = 'DELETE_USER';
export const SET_LOADER = 'SET_LOADER';
export const SET_TOOLTIP = 'SET_TOOLTIP';